function [ z0 ] = ShowSegment( WaveGuideSegment, z0 )

a = WaveGuideSegment.a;
b = WaveGuideSegment.b;
l = WaveGuideSegment.l;
xo = WaveGuideSegment.xo;
yo = WaveGuideSegment.yo;

patch([xo-a/2, xo+a/2, xo+a/2, xo-a/2],...
    [yo-b/2, yo-b/2, yo-b/2, yo-b/2],...
    [z0, z0, z0+l, z0+l],'b');

patch([xo-a/2, xo+a/2, xo+a/2, xo-a/2],...
    [yo+b/2, yo+b/2, yo+b/2, yo+b/2],...
    [z0, z0, z0+l, z0+l],'b');

patch([xo-a/2, xo-a/2, xo-a/2, xo-a/2],...
    [yo-b/2, yo+b/2, yo+b/2, yo-b/2],...
    [z0, z0, z0+l, z0+l],'b');

patch([xo+a/2, xo+a/2, xo+a/2, xo+a/2],...
    [yo-b/2, yo+b/2, yo+b/2, yo-b/2],...
    [z0, z0, z0+l, z0+l],'b');

z0 = z0+l;