function GSMDraw(f, Sf, Sinfo, ModeStruct, flag)
% GSMDraw(f,Sf,Sinfo,...
%     {{1,3,'h',1,0,'h',1,0,'md'};...
%      {2,3,'h',1,0,'h',1,0,'md'};...
%      {3,3,'h',1,0,'h',1,0,'md'};...
%      {3,3,'h',1,1,'h',1,0,'md'};...
%      {3,3,'h',1,3,'h',1,0,'md'};...
%      {3,3,'e',1,1,'h',1,0,'md'};...
%      {3,3,'e',1,3,'h',1,0,'md'};...
%      });
% S11_h10 = ExtractSingleS(Sf{nf},Sinfo,1,1,'h',1,0,'h',1,0);

Color =[' k-',' r-',' g-',' b-',' y-',' m-',' c-'];
Legend = [];
if(flag)
    figure
    for Plot_nbr=1:length(ModeStruct)
        Plot_infos = ModeStruct{Plot_nbr};
        outPort = Plot_infos{1};
        inPort = Plot_infos{2};
        outMode = Plot_infos{3};
        outMode_m = Plot_infos{4};
        outMode_n = Plot_infos{5};
        inMode = Plot_infos{6};
        inMode_m = Plot_infos{7};
        inMode_n = Plot_infos{8};
        % md = Plot_infos{9};
        for nf=1:length(f)
            S{Plot_nbr}(nf) = ...
                ExtractSingleS(Sf{nf},Sinfo,outPort,inPort,outMode,...
                outMode_m,outMode_n,inMode,inMode_m,inMode_n);
        end
        hold on;
        plot(f,20*log10(abs(S{Plot_nbr})),char(Color(Plot_nbr*3-2),Color(Plot_nbr*3-1),...
            Color(Plot_nbr*3)));
        ModesLegend = char( ...
            ['S',int2str(outPort), int2str(inPort),'_{', ...
            outMode, int2str(outMode_m), int2str(outMode_n),'_{', ...
            inMode, int2str(inMode_m), int2str(inMode_n),'}}'] ...
            );
        Legend = strvcat(Legend, ModesLegend);
    end
    legend(Legend);
    axis([min(f) max(f) -60 0]);
end