/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.4 and the Signal Processing Toolbox 6.7.
 *
 * Generated on: 04-Jun-2008 15:25:22
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 32
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */

/* 
 * Expected path to tmwtypes.h 
 * C:\Programmi\MATLAB\R2007a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */


int h[32] = {
      102,    159,    207,    335,    435,    597,    740,    925,   1093,
     1282,   1448,   1613,   1746,   1859,   1933,   1973,   1973,   1933,
     1859,   1746,   1613,   1448,   1282,   1093,    925,    740,    597,
      435,    335,    207,    159,    102
};
